### ISSUE TITLE
Convert in-game HUD graphics to MODE 5

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#18]
For now assume fixed palette in MODE 5 but may think about palette swap for the bottom HUD portion.

**Comment by tom-seddon** [comment]
Pixel format fixed by 538407229d57f1770e3eda6173f329cc31ae8d1e. The palette remains an open question...

**Comment by kieranhj** [comment]
This can be closed as we're not going to change the palette in game.
