### ISSUE TITLE
Redefine keys doesn't work

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#21]
Not sure if this is just that the text isn't being displayed, whether F1 isn't being detected, or whether it's just plain bust.

**Comment by kieranhj** [comment]
Text in game is done via sprites, sprites are done via IRQ interrupts. The pause puts the game in a tight loop with no screen update other than that achieved via IRQ handler (i.e. sprites.) Need to think about how this would be done on Beeb.

**Comment by tom-seddon** [comment]
Fixed by 6c54bcfe4f2cc4f517d8541529593cde2f8b9ca6
