### ISSUE TITLE
Extract UI graphics

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/scr-beeb#23]
Looks like the UI graphics are going to need at least a bit of manual fixing. Turn the data into PNGs, then write a quick script to turn PNGs back into data.

The front end header graphic has some kind of RLE-type compression applied. Probably just need to turn this into a single image, so that there's no need to make sure the compressed version is the same size as it was.

**Comment by kieranhj** [comment]
Anything left here?

**Comment by tom-seddon** [comment]
Don't think so. Can always add a new issue if we find otherwise!
