### ISSUE TITLE
Extension: add winner / wrecked screens from 16-bit version

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#26]
Screens from the 16-bit version of the game could be stashed in SWRAM and compressed with pucrunch. Decompress to SHADOW RAM screen to avoid disturbing the main game configuration.

**Comment by tom-seddon** [comment]
I've put 320x200 versions of the test screens in the repo, and added the png2bbc/pucrunch steps to the Makefile. (No problem that the batch file doesn't do this - the data isn't used yet.)

Wrecked screen = 5,365 bytes
Winner screen = 4,731 bytes

There's only 5,669 bytes free in sideways RAM, and that's across 3 banks, so there'd be some shuffling, or packing in parts, to fit even 1 in.

The credits screen image is 3,524 bytes packed, so rethinking that won't free up enough room.

The 4th bank is provisionally booked for music.

I'm tempted to say no to this. Do we even know where we'd need to put the code to show this stuff anyway? :)

**Comment by kieranhj** [comment]
I think we can close this as a step too far. The screens look cool but then the Amiga version has loads of other graphical niceties, including driver pictures etc.
