### ISSUE TITLE
Hide glitch when switching between video modes

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#28]
Currently get a frame of crap when vertical rupture is first enabled. Just hide with a blank screen.

**Comment by kieranhj** [comment]
Also some glitches when switching between MODE 2 title and MODE 1 menu screens.
Generally need a polish pass to remove glitches and/or hide screen during transitions.

**Comment by kieranhj** [comment]
Think about adding *FX19 to avoid changing CRTC registers during visible frame.

**Comment by tom-seddon** [comment]
Fixed by 5f461cd7ceff4a03105018efa85fae6dbb7447e0
