### ISSUE TITLE
Cracks don't draw on top of the dithered areas on the HUD

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/scr-beeb#31]
I think it's due to the black pixels, and https://github.com/kieranhj/scr-beeb/blob/99296e67a4703f1851140aa02e5d6843a01a9253/game/cart-ram.asm#L4629 - maybe??

Presumably stops it drawing cracks on top of the holes.

**Comment by kieranhj** [comment]
Do we need the top line of the HUD changing or can we work around it somehow?

**Comment by kieranhj** [comment]
Tom fixed this.
