### ISSUE TITLE
Extension: remove unnecessary C64 code

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#37]
Is it worth removing any code that's poking C64 VIC registers etc.? At the moment it's fairly harmless as it's mapped into Hazel. Balance to be struck here between completeness and potential bugs..!

**Comment by tom-seddon** [comment]
Since it's now all mapped to somewhere in page 3, I think it's probably safe to leave it.

I have been removing this stuff when I spot it.
