### ISSUE TITLE
Not sure what's going on with the two small dashboard icons

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#41]
There are two icons on the dashboard - checkered flag and clock? Do these light up under various conditions (e.g. in the lead when playing against AI?)

Also not sure if they've come through the conversion correctly process with Dethmunk's new HUD png.

**Comment by tom-seddon** [comment]
The flag lights up when you're in the lead, and the stopwatch lights up when you've got the best lap (can't remember if it lights up in practice mode too).

The code isn't designed to operate on the new multicolour type of icon, so I'll fix that up.
