### ISSUE TITLE
Find and fix vertical rupture timing problem with VLSI 6845 chips

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#50]
@tom-seddon reported that his Master has an occasional glitch during gameplay that does not occur on my machine - suspect that there is a timing problem with the vertical rupture which the VLSI 6845 chip in his machine does not like.

**Comment by tom-seddon** [comment]
I will look at this at some point this weekend.

**Comment by tom-seddon** [comment]
Fingers crossed that a9568302439869542ce5080230ac2cb189d20dd1 is the fix...
