### ISSUE TITLE
Hall of Fame screen looks ugly as sin

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#51]
Either need to come up with a better colour map fill routine or some sort of fancy pucrunched screen that all of the text can be blatted on top of.

**Comment by tom-seddon** [comment]
35d9f8078297d624eb6101a120aa41ac39e4bfa2 fixed two obvious issues.

**Comment by kieranhj** [comment]
Pinged Dethmunk to see whether he has the bandwidth to create a custom screen for this.

**Comment by kieranhj** [comment]
We have a screen - going to try putting it in to see what it looks like.

**Comment by kieranhj** [comment]
Looks great! Done in branch `wip/hall-fame` to be merged shortly.

**Comment by tom-seddon** [comment]
Fixed by a06fc23308abcc1579cc128050a324fc5f792398
