### ISSUE TITLE
Free up more of HAZEL

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/scr-beeb#53]
HAZEL is looking emptier, but there's still some stuff in there that could probably be moved to cart RAM:

* $C000 - $C27F - engine graphics bits, I think
* $C280...$C2FF - initial values for horizon table

There are various tables at (at least) $c300...$c6ff.

They could go in cart RAM, if the line draw routines were moved out of kernel RAM, but it doesn't look like there'd be room for all of this stuff. Would maybe need some more shuffling around...

**Comment by tom-seddon** [comment]
If there's enough for DFS OSFILE to work, I think we can decide this is done.

**Comment by kieranhj** [comment]
I think we're good here. I had to nab some more pages for the save game file operations but there are still 2x pages left safely.
