### ISSUE TITLE
Make in-game text look a bit neater

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/scr-beeb#54]
The in-game text is solid red, which is fine, and stands out - but would it look better with an outline?

The ST/Amiga versions have the pause/redefine keys messages appear in a little box with a border round it. That might be worth doing. The pause mode runs without double buffering, so this would actually simplify the code in a couple of places.

**Comment by kieranhj** [comment]
Looks alright to me?

**Comment by tom-seddon** [comment]
Let's close it then :)
