### ISSUE TITLE
Extension: implement C64 trainer options?

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#57]
The C64 version has a trainer before the main game that allows a number of cheat options to make the game easier for novice players. Given that we're not generally as good at games as we were in the 80's it might be nice to help out the oldies. I certainly found that people valued this for POP.

**Comment by kieranhj** [comment]
These are:
> Do you want endless boost? Y/N
> Do you want endless damage? Y/N
> Crashes are very much faster? Y/N
> Opponents cannot win? Y/N
> Press 'Q' to win current race? Y/N

All are implemented by a single byte poke to twiddle the game code.
If selecting the trainer mode then the save game is also nerfed so you can't save high scores / progress.

**Comment by kieranhj** [comment]
I think this would be worth looking at.

**Comment by tom-seddon** [comment]
Fixed by 40699234487e21cf456717cc7a5525ae826f9341
