### ISSUE TITLE
Additional guff at sides of game screen

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#6]
There is some guff on the left and right hand sides of the main game screen that aren't visible in the C64 version - not sure why or how it's been copied there.

**Comment by kieranhj** [comment]
This guff is actually the border for the track preview! Presumably hidden on C64 by colour map...

**Comment by tom-seddon** [comment]
Fixed by f14c351c346995209d5d627fe4ebb2bec11a9fcb
