### ISSUE TITLE
file_strings could be in kernel RAM?

### ISSUE THREAD

**Issue by tom-seddon** [kieranhj/scr-beeb#64]
I think `file_strings` and `file_strings_offsets` could be moved in to kernel RAM. Looks like they aren't accessed from anywhere else.

It's accessed from the routine `L_95DE` in cart-ram.asm, but that doesn't appear to be called from anywhere, so it can probably go...

**Comment by kieranhj** [comment]
Done in branch `wip/hall-fame`.

**Comment by tom-seddon** [comment]
Fixed by c40451017aeb52a7b0bd619417b549b6ef69defc
